/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrame;

import LibraryManagement.ConnectMSSQL;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author AsadullauhSojib
 */
public class BookReservation extends javax.swing.JFrame {

    /**
     * Creates new form BookReservation
     */
    public BookReservation() {
        initComponents();
    }
    public void getBookDetails() {
        int bookId = Integer.parseInt(reserve_txt_bookId.getText());
        try {
            Connection con = ConnectMSSQL.connectDB();
            String sql = "select * from book_details where bookId =?";
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setInt(1, bookId);

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                reserve_bookId.setText(rs.getString("bookId"));
                reserve_bookName.setText(rs.getString("bookName"));
                reserve_author.setText(rs.getString("author"));
                reserve_quantity.setText(rs.getString("quantity"));
            } else {
                issue_bookError.setText("Invalid Book ID!!");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void getStudentDetails() {
        int studentId = Integer.parseInt(reserve_txt_studentId.getText());
        try {
            Connection con = ConnectMSSQL.connectDB();
            String sql = "select * from student_details where studentId =?";
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setInt(1, studentId);

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                reserve_studentId.setText(rs.getString("studentId"));
                reserve_studentName.setText(rs.getString("name"));
                reserve_department.setText(rs.getString("department"));
                reserve_branch.setText(rs.getString("branch"));
            } else {
                issue_studentError.setText("Invalid Student ID!!");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public boolean reserveBook(){
        boolean isReserved = false;
        int bookId = Integer.parseInt(reserve_txt_bookId.getText());
        int studentId=Integer.parseInt(reserve_txt_studentId.getText());
        
        String bookName = reserve_bookName.getText();
        String studentName = reserve_studentName.getText();
        
        java.util.Date reservedDate =reserve_ReservationDate.getDate();
        
        Long l1 = reservedDate.getTime();
        
        Date sqlreserveDate = new Date(l1);
//          
          try {
              Connection con = ConnectMSSQL.connectDB();
              String sql = "insert into reservation_details (bookId,bookName,studentId,studentName,"+"reservationDate) values(?,?,?,?,?)";
              PreparedStatement pst = con.prepareStatement(sql);
              
              pst.setInt(1, bookId);
              pst.setString(2, bookName);
              pst.setInt(3, studentId);
              pst.setString(4, studentName);
              pst.setDate(5, sqlreserveDate);
              
              int rowCount = pst.executeUpdate();
              if(rowCount>0){
                  isReserved = true;
              }else
                  isReserved=false;
              
              
            } catch (Exception e) {
                  e.printStackTrace();
            }
          return isReserved;
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        reserve_branch = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        reserve_studentId = new javax.swing.JLabel();
        reserve_studentName = new javax.swing.JLabel();
        reserve_department = new javax.swing.JLabel();
        issue_studentError = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        reserve_bookId = new javax.swing.JLabel();
        reserve_quantity = new javax.swing.JLabel();
        reserve_author = new javax.swing.JLabel();
        reserve_bookName = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        issue_bookError = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        reserve_txt_bookId = new app.bolivia.swing.JCTextField();
        jLabel16 = new javax.swing.JLabel();
        reserve_txt_studentId = new app.bolivia.swing.JCTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        rSMaterialButtonCircle2 = new necesario.RSMaterialButtonCircle();
        reserve_ReservationDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("Branch");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        jLabel3.setFont(new java.awt.Font("STXihei", 0, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Student_Registration_100px_2.png"))); // NOI18N
        jLabel3.setText("Student Details");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        reserve_branch.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        reserve_branch.setForeground(new java.awt.Color(255, 255, 204));
        jPanel2.add(reserve_branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 240, 30));

        jLabel5.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("Student Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel6.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("Department");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        jLabel13.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 204));
        jLabel13.setText("Student ID");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        reserve_studentId.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        reserve_studentId.setForeground(new java.awt.Color(255, 255, 204));
        jPanel2.add(reserve_studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 240, 30));

        reserve_studentName.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        reserve_studentName.setForeground(new java.awt.Color(255, 255, 204));
        jPanel2.add(reserve_studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 240, 30));

        reserve_department.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        reserve_department.setForeground(new java.awt.Color(255, 255, 204));
        jPanel2.add(reserve_department, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 240, 30));

        issue_studentError.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        issue_studentError.setForeground(new java.awt.Color(255, 255, 102));
        jPanel2.add(issue_studentError, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 350, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 420, 820));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 0, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 204));
        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel7.setText("Back");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 30));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 50));

        jLabel9.setFont(new java.awt.Font("STXihei", 0, 25)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 204));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel9.setText("Book Details");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 204));
        jLabel10.setText("Book ID");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel11.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 204));
        jLabel11.setText("Book Name");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel12.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 204));
        jLabel12.setText("Author");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        reserve_bookId.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        reserve_bookId.setForeground(new java.awt.Color(255, 255, 204));
        jPanel4.add(reserve_bookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 240, 30));

        reserve_quantity.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        reserve_quantity.setForeground(new java.awt.Color(255, 255, 204));
        jPanel4.add(reserve_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 240, 30));

        reserve_author.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        reserve_author.setForeground(new java.awt.Color(255, 255, 204));
        jPanel4.add(reserve_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 240, 30));

        reserve_bookName.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        reserve_bookName.setForeground(new java.awt.Color(255, 255, 204));
        jPanel4.add(reserve_bookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 240, 30));

        jLabel14.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 204));
        jLabel14.setText("Quantity");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        issue_bookError.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        issue_bookError.setForeground(new java.awt.Color(255, 255, 0));
        jPanel4.add(issue_bookError, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 330, 50));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 820));

        jLabel4.setFont(new java.awt.Font("STXihei", 0, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        jLabel4.setText("Book Reservation");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 110, -1, -1));

        jPanel7.setBackground(new java.awt.Color(51, 0, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("STXinwei", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(" X");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 0, 50, -1));

        reserve_txt_bookId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 0, 51)));
        reserve_txt_bookId.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        reserve_txt_bookId.setPhColor(new java.awt.Color(51, 0, 51));
        reserve_txt_bookId.setPlaceholder("Enter Book ID...");
        reserve_txt_bookId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                reserve_txt_bookIdFocusLost(evt);
            }
        });
        reserve_txt_bookId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserve_txt_bookIdActionPerformed(evt);
            }
        });
        jPanel1.add(reserve_txt_bookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 370, 320, 30));

        jLabel16.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 51));
        jLabel16.setText("Book ID");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 380, -1, -1));

        reserve_txt_studentId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 0, 51)));
        reserve_txt_studentId.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        reserve_txt_studentId.setPhColor(new java.awt.Color(51, 0, 51));
        reserve_txt_studentId.setPlaceholder("Enter Student ID...");
        reserve_txt_studentId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                reserve_txt_studentIdFocusLost(evt);
            }
        });
        reserve_txt_studentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserve_txt_studentIdActionPerformed(evt);
            }
        });
        jPanel1.add(reserve_txt_studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 450, 320, 30));

        jLabel18.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 0, 51));
        jLabel18.setText("Student ID");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 460, -1, -1));

        jLabel20.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 0, 51));
        jLabel20.setText("Reservation Date");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 540, -1, -1));

        rSMaterialButtonCircle2.setBackground(new java.awt.Color(51, 0, 51));
        rSMaterialButtonCircle2.setForeground(new java.awt.Color(255, 255, 204));
        rSMaterialButtonCircle2.setLabel("RESERVE BOOK");
        rSMaterialButtonCircle2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonCircle2MouseClicked(evt);
            }
        });
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 630, 270, 60));

        reserve_ReservationDate.setBackground(new java.awt.Color(255, 255, 255));
        reserve_ReservationDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 102, 102)));
        reserve_ReservationDate.setDateFormatString("yyyy/MM/dd");
        reserve_ReservationDate.setFont(new java.awt.Font("STXihei", 0, 17)); // NOI18N
        jPanel1.add(reserve_ReservationDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 530, 320, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1456, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        HomePage home = new HomePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void reserve_txt_bookIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reserve_txt_bookIdFocusLost
        // TODO add your handling code here:
        if (!reserve_txt_bookId.getText().equals("")) {
            getBookDetails();
        }
    }//GEN-LAST:event_reserve_txt_bookIdFocusLost

    private void reserve_txt_bookIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserve_txt_bookIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reserve_txt_bookIdActionPerformed

    private void reserve_txt_studentIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reserve_txt_studentIdFocusLost
        // TODO add your handling code here:
        if (!reserve_txt_studentId.getText().equals("")) {
            getStudentDetails();
        }
    }//GEN-LAST:event_reserve_txt_studentIdFocusLost

    private void reserve_txt_studentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserve_txt_studentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reserve_txt_studentIdActionPerformed

    private void rSMaterialButtonCircle2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle2MouseClicked

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
        //TODO add your handling code here:
        if (reserve_quantity.getText().equals("0")) {
            JOptionPane.showMessageDialog(this, "Book Is Not Available");

        }
        
        if (reserveBook() == true) {
                    JOptionPane.showMessageDialog(this, "Book Reserved Successfully");
                    
        }else
                    JOptionPane.showMessageDialog(this, "Can't Reserve This Book");
    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel issue_bookError;
    private javax.swing.JLabel issue_studentError;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private com.toedter.calendar.JDateChooser reserve_ReservationDate;
    private javax.swing.JLabel reserve_author;
    private javax.swing.JLabel reserve_bookId;
    private javax.swing.JLabel reserve_bookName;
    private javax.swing.JLabel reserve_branch;
    private javax.swing.JLabel reserve_department;
    private javax.swing.JLabel reserve_quantity;
    private javax.swing.JLabel reserve_studentId;
    private javax.swing.JLabel reserve_studentName;
    private app.bolivia.swing.JCTextField reserve_txt_bookId;
    private app.bolivia.swing.JCTextField reserve_txt_studentId;
    // End of variables declaration//GEN-END:variables
}
