/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrame;

import LibraryManagement.ConnectMSSQL;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author AsadullauhSojib
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public ReturnBook() {
        initComponents();
    }
    public void getIssueBookDetails(){
        //boolean success=false;
        int bookId = Integer.parseInt(return_txt_bookId.getText());
        int studentID = Integer.parseInt(return_txt_studentId.getText());
        
        try {
            Connection con = ConnectMSSQL.connectDB();
            String sql = "select * from issue_book_details where bookId=? and studentId = ? and state =?";
            PreparedStatement pst = con.prepareStatement(sql);
            
            pst.setInt(1, bookId);
            pst.setInt(2, studentID);
            pst.setString(3, "pending");
            
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                //success=true;
                return_issueId.setText(rs.getString("issueId"));
                return_bookName.setText(rs.getString("bookName"));
                return_studentName.setText(rs.getString("studentName")); 
                return_issueDate.setText(rs.getString("issueDate"));
                return_dueDate.setText(rs.getString("dueDate"));
                return_bookError.setText("");
            }else{
                //success = false;
                return_issueId.setText("");
                return_bookName.setText("");
                return_studentName.setText(""); 
                return_issueDate.setText("");
                return_dueDate.setText("");
                return_bookError.setText("No Record Found");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
      //  return success;
    }
    
    public boolean returnBook(){
        boolean isReturned = false;
        int bookId = Integer.parseInt(return_txt_bookId.getText());
        int studentID = Integer.parseInt(return_txt_studentId.getText());
        
        try {
            Connection con = ConnectMSSQL.connectDB();
            String sql = "update issue_book_details set state=? where studentId=? and bookId=? and state=?";
            PreparedStatement pst = con.prepareStatement(sql);
            
            pst.setString(1, "Returned");
            pst.setInt(2, studentID);
            pst.setInt(3, bookId);
            pst.setString(4, "pending");
            
            int rowCount = pst.executeUpdate();
            if(rowCount>0){
                isReturned = true;
            }
            else{
                isReturned = false;
            }
            
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        return isReturned;
    }
    public void updateBookCount(){
        int bookId = Integer.parseInt(return_txt_bookId.getText());
        try {
            Connection con = ConnectMSSQL.connectDB();
            String sql = "update book_details set quantity = quantity+1 where bookId=?";
            PreparedStatement pst = con.prepareStatement(sql);
            
            pst.setInt(1, bookId);
            
            int rowCount =pst.executeUpdate();
            
            if(rowCount>0){
                JOptionPane.showMessageDialog(this, "Book Count Updated");
                             
            }else
                JOptionPane.showMessageDialog(this, "Can't Update Book Count");
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        return_issueId = new javax.swing.JLabel();
        return_dueDate = new javax.swing.JLabel();
        return_studentName = new javax.swing.JLabel();
        return_bookName = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        return_bookError = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        return_issueDate = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        return_txt_studentId = new app.bolivia.swing.JCTextField();
        return_txt_bookId = new app.bolivia.swing.JCTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        rSMaterialButtonCircle2 = new necesario.RSMaterialButtonCircle();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        rSMaterialButtonCircle3 = new necesario.RSMaterialButtonCircle();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("STXihei", 0, 25)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 204));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel9.setText("Book Details");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 204));
        jLabel10.setText("Issue ID");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        jLabel11.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 204));
        jLabel11.setText("Book Name");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jLabel12.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 204));
        jLabel12.setText("Student Name");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        return_issueId.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        return_issueId.setForeground(new java.awt.Color(255, 255, 204));
        jPanel4.add(return_issueId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 240, 30));

        return_dueDate.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        return_dueDate.setForeground(new java.awt.Color(255, 255, 204));
        jPanel4.add(return_dueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 650, 240, 30));

        return_studentName.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        return_studentName.setForeground(new java.awt.Color(255, 255, 204));
        jPanel4.add(return_studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 240, 30));

        return_bookName.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        return_bookName.setForeground(new java.awt.Color(255, 255, 204));
        jPanel4.add(return_bookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 240, 30));

        jLabel14.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 204));
        jLabel14.setText("Due Date");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, -1, -1));

        return_bookError.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        return_bookError.setForeground(new java.awt.Color(255, 255, 0));
        jPanel4.add(return_bookError, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 720, 330, 50));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("STXinwei", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(" X");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 50, 50));

        jLabel21.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 204));
        jLabel21.setText("Issue Date");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, -1));

        return_issueDate.setFont(new java.awt.Font("STXihei", 0, 20)); // NOI18N
        return_issueDate.setForeground(new java.awt.Color(255, 255, 204));
        jPanel4.add(return_issueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 240, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 380, 800));

        jPanel7.setBackground(new java.awt.Color(51, 0, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 10, 50, -1));

        return_txt_studentId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 0, 51)));
        return_txt_studentId.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        return_txt_studentId.setPhColor(new java.awt.Color(51, 0, 51));
        return_txt_studentId.setPlaceholder("Enter Student ID...");
        return_txt_studentId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                return_txt_studentIdFocusLost(evt);
            }
        });
        return_txt_studentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_txt_studentIdActionPerformed(evt);
            }
        });
        jPanel1.add(return_txt_studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 320, 30));

        return_txt_bookId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 0, 51)));
        return_txt_bookId.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        return_txt_bookId.setPhColor(new java.awt.Color(51, 0, 51));
        return_txt_bookId.setPlaceholder("Enter Book ID...");
        return_txt_bookId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                return_txt_bookIdFocusLost(evt);
            }
        });
        return_txt_bookId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                return_txt_bookIdActionPerformed(evt);
            }
        });
        jPanel1.add(return_txt_bookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 320, 30));

        jLabel16.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 51));
        jLabel16.setText("Book ID");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("STXihei", 0, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        jLabel4.setText("Return Books");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, -1, -1));

        jLabel18.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 0, 51));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/Loginpage.jpeg"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 88, 470, 640));

        rSMaterialButtonCircle2.setBackground(new java.awt.Color(51, 0, 51));
        rSMaterialButtonCircle2.setForeground(new java.awt.Color(255, 255, 204));
        rSMaterialButtonCircle2.setText("Return Book");
        rSMaterialButtonCircle2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonCircle2MouseClicked(evt);
            }
        });
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 590, 270, 60));

        jPanel5.setBackground(new java.awt.Color(51, 0, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 204));
        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel7.setText("Back");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 50));

        rSMaterialButtonCircle3.setBackground(new java.awt.Color(51, 0, 51));
        rSMaterialButtonCircle3.setForeground(new java.awt.Color(255, 255, 204));
        rSMaterialButtonCircle3.setText("Find");
        rSMaterialButtonCircle3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonCircle3MouseClicked(evt);
            }
        });
        rSMaterialButtonCircle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 270, 60));

        jLabel19.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 0, 51));
        jLabel19.setText("Student ID");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 205, 340, 5));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 800));

        setSize(new java.awt.Dimension(1408, 803));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        HomePage home = new HomePage();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void return_txt_bookIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_return_txt_bookIdFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_return_txt_bookIdFocusLost

    private void return_txt_bookIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_txt_bookIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_return_txt_bookIdActionPerformed

    private void return_txt_studentIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_return_txt_studentIdFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_return_txt_studentIdFocusLost

    private void return_txt_studentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_return_txt_studentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_return_txt_studentIdActionPerformed

    private void rSMaterialButtonCircle2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle2MouseClicked

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
        //TODO add your handling code here:
        if (returnBook() == true) {
            JOptionPane.showMessageDialog(this, "Book returned Successfully");
            updateBookCount();
        }else
            JOptionPane.showMessageDialog(this, "Book returned Failed");
            
                
    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    private void rSMaterialButtonCircle3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonCircle3MouseClicked

    private void rSMaterialButtonCircle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle3ActionPerformed
        // TODO add your handling code here:
        getIssueBookDetails();
    }//GEN-LAST:event_rSMaterialButtonCircle3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle3;
    private javax.swing.JLabel return_bookError;
    private javax.swing.JLabel return_bookName;
    private javax.swing.JLabel return_dueDate;
    private javax.swing.JLabel return_issueDate;
    private javax.swing.JLabel return_issueId;
    private javax.swing.JLabel return_studentName;
    private app.bolivia.swing.JCTextField return_txt_bookId;
    private app.bolivia.swing.JCTextField return_txt_studentId;
    // End of variables declaration//GEN-END:variables
}
